### ISSUE TITLE
How to fix a bricked head unit

### ISSUE THREAD

**Issue by mcmayer** [OpenHamradioFirmware/G90Tools#2]
Long story short: I managed to brick my head unit, my guess is that RF ingress via the CAT cable damaged the MCU in the head unit. You've done fantastic work on figuring out the firmware update mechanics. I'm not sure I fully understood the IP protection mechanisms. Hence my question: If I replace the (presumably) damaged MCU, is it possible to flash the bootloader on a fresh STM32F103 in the head unit?

**Comment by kbeckmann** [comment]
> is it possible to flash the bootloader on a fresh STM32F103 in the head unit

Yes, however you need the bootloader binary. Since it's proprietary firmware I can't share it. You would have to extract the firmware from another unit and then flash the bootloader manually. You could either then perform a firmware update to the version you want to run from official sources, or flash the extracted application binary manually as well.

It is possible that your MCU is not broken, and that external circuitry is broken instead.

I would first check if the stm32 is working at all. To do this you need a debugger that can talk to the stm32. ST-Link v2, J-Link, raspberry pi etc will do (however I have only tested this with an ST-Link v2). Using this, you can try to connect to the stm32 over the SWD port and see if you get a connection. If you do, then the stm32 is working - you could extract firmware. However, you wouldn't really need to since the problem is elsewhere in that case :).

**Comment by kbeckmann** [comment]
Btw, you might be interested in https://git.xil.se/hamclub/catconnect to isolate your unit. It's a project I worked on that has a USB hub, audio codec, and UART-to-USB. All signals going to the radio are isolated - uart using ISO7021DR, audio through isolation transformers.

It's more or less a dead project but it works, I've built a few, and no firmware is needed.

**Comment by mcmayer** [comment]
In fact, as you suspected, there is an issue with the external circuitry already. It seems that R44 and R45 (inadvertently?) acted as fuses, both look very much torched. Let's see, maybe I'm lucky.
Your `catconnect` is a great project, by the way!
